name: agriot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0 
  firebase_auth: ^4.20.0 
  firebase_database: ^10.5.7
  syncfusion_flutter_charts: ^26.1.41
  web3dart: ^2.7.3
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

